baseURL = "https://slayhoccode.github.io/"
languageCode = "vi"
title = "Blog L·∫≠p Tr√¨nh M·∫°ng"
theme = "PaperMod"

publishDir = "docs"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true

[params.homeInfoParams]
  Title = "Ch√†o m·ª´ng ƒë·∫øn v·ªõi Blog c·ªßa t√¥i üëã"
  Content = "Chia s·∫ª ki·∫øn th·ª©c v·ªÅ l·∫≠p tr√¨nh Java & JavaScript"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/slayhoccode"

[[params.socialIcons]]
  name = "email"
  url = "mailto:phamtraidz@gmail.com"

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "posts"
  name = "Blog"
  url = "/posts/"
  weight = 20

[[menu.main]]
  identifier = "about"
  name = "Gi·ªõi thi·ªáu"
  url = "/about/"
  weight = 30